sources:
  telegram:
    enable: true
    session_name: "session_windows"
    info:
      last_n_messages: 50
      channels:
        - visa_randevu
        - iDataanlikrandevu
        - AlmanyaVizeveDenklik
